server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  undertow:
    url-charset: UTF-8

spring:
  profiles:
    active: dev
  messages:
    encoding: UTF-8
    basename: i18n/messages

mybatis:
#  mapper-locations: classpath*:com/mega/tweaks/api/model/dao/*.xml
  type-aliases-package: com.mega.tweaks.api.model.entity
  configuration:
    map-underscore-to-camel-case: true