server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  undertow:
    url-charset: UTF-8
spring:
  messages:
    encoding: UTF-8
    basename: i18n/messages