spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://coder.53site.com:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&cachePrepStmts=true&prepStmtCacheSize=256&prepStmtCacheSqlLimit=2048&useServerPrepStmts=true&useLocalSessionState=true&rewriteBatchedStatements=true&cacheResultSetMetadata=true&cacheServerConfiguration=true&elideSetAutoCommits=true&maintainTimeStats=false&zeroDateTimeBehavior=convertToNull
    username: admin
    password: Mangosteen0!
  # mongodb
  data:
    mongodb:
      uri: mongodb://112.124.15.145:27117/test?maxPoolSize=500&minPoolSize=10
  redis:
    db0:
      host: 112.124.15.145
      port: 6379
      database: 0
      password: LA1954b!
    db3:
      host: 112.124.15.145
      port: 6379
      database: 3
      password: LA1954b!
    db8:
      host: 112.124.15.145
      port: 6379
      database: 8
      password: LA1954b!
  kafka:
    bootstrap-servers: 114.55.124.235:9992
    producer:
      acks: 0
      retries: 0
      properties:
        linger.ms: 1000

metabus:
  node_role: "master"