server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
    context-path: /${spring.profiles.active}
  undertow:
    url-charset: UTF-8

spring:
  profiles:
    active: dev
  messages:
    encoding: UTF-8
    basename: i18n/messages

mybatis:
  configuration:
    map-underscore-to-camel-case: true